export const LIVE_SHEET_TABS = [
  "Staff",
  "Dashboard",
  "Customers",
  "Orders",
  "Rewards",
  "Loyalty Winners",
  "Generated Vouchers",
  "Reward Redemptions",
  "Unpaid Tracker",
  "Menu",
  "Payments",
  "Lists",
  "Day History",
  "Order Items",
  "Audit Log",
  "Sync Failures",
  "Customer Summary",
  "Daily Receipt Files",
  "Business Settings",
  "Schema Status",
] as const;

export type NormalizedSheetName = (typeof LIVE_SHEET_TABS)[number];

export const NORMALIZED_SHEETS = {
  auditLog: "Audit Log",
  businessSettings: "Business Settings",
  customerSummary: "Customer Summary",
  customers: "Customers",
  dailyReceiptFiles: "Daily Receipt Files",
  dayHistory: "Day History",
  generatedVouchers: "Generated Vouchers",
  menu: "Menu",
  orderItems: "Order Items",
  orders: "Orders",
  payments: "Payments",
  redemption: "Reward Redemptions",
  schemaStatus: "Schema Status",
  staff: "Staff",
  syncFailures: "Sync Failures",
} as const satisfies Record<string, NormalizedSheetName>;

export const NORMALIZED_SHEET_HEADERS: Record<NormalizedSheetName, string[]> = {
  Staff: [
    "Email",
    "Password",
    "Role",
    "Name",
    "Active",
    "displayName",
    "uid",
    "grant",
    "revoke",
    "updatedAt",
  ],
  Dashboard: ["Joy Corner Staff Database"],
  Customers: [
    "Customer ID",
    "Full Name",
    "Phone/WhatsApp",
    "Join Date",
    "Birthday",
    "Favorite Drink",
    "Notes",
    "Active?",
    "Total Orders",
    "Total Spent",
    "Paid Amount",
    "Unpaid Balance",
    "Points",
    "Free Drinks",
    "Last Visit",
    "Current Balance",
    "Paid Drinks",
    "Free Drinks Ready",
    "Last Visit Auto",
    "phone",
    "email",
    "createdAt",
    "updatedAt",
  ],
  Orders: [
    "Order Date/Time",
    "Customer ID",
    "Customer Name",
    "Staff",
    "Category",
    "Item",
    "Qty",
    "Unit Price",
    "Discount",
    "Total",
    "Points Earned",
    "Points Redeemed",
    "Payment Status",
    "Order Status",
    "Notes",
    "orderId",
    "receiptNumber",
    "businessDate",
    "customerPhone",
    "serviceType",
    "orderPlace",
    "itemCount",
    "itemSummary",
    "itemsJson",
    "categorySummary",
    "subtotal",
    "itemDiscountTotal",
    "orderDiscount",
    "paidAmount",
    "remainingAmount",
    "outstandingAmount",
    "changeAmount",
    "paymentMethod",
    "clientRequestId",
    "createdAt",
    "customerNameSnapshot",
    "customerPhoneSnapshot",
    "staffUid",
    "staffName",
    "staffRole",
    "serviceTypeMigrationDuplicate",
    "orderPlaceMigrationDuplicate",
    "discountTotal",
    "rewardDiscount",
    "tax",
    "serviceCharge",
    "amountReceived",
    "customerNotes",
    "activeBoard",
    "archived",
    "archivedAt",
    "archiveBatchId",
    "dailyPdfId",
    "createdByUid",
    "createdByEmail",
    "updatedAt",
    "amountApplied",
  ],
  Rewards: [
    "Customer ID",
    "Customer Name",
    "Phone",
    "Paid Drinks",
    "Free Drinks Ready",
    "Next Reward Progress",
    "Last Visit",
    "Favorite Drink",
    "Loyalty Card Winner?",
    "Redeem Status",
    "Winner Message",
  ],
  "Loyalty Winners": ["Joy Corner Loyalty Card Winners"],
  "Generated Vouchers": [
    "Voucher Code",
    "Customer ID",
    "Customer Name",
    "Phone",
    "Favorite Drink",
    "Voucher Title",
    "Voucher Subtitle",
    "Voucher Text",
    "Voucher Reward",
    "Redeem Status",
    "Generated At",
    "fullName",
    "phoneWhatsApp",
    "createdAt",
    "date",
  ],
  "Reward Redemptions": [
    "Redemption ID",
    "Date",
    "Customer ID",
    "Customer Name",
    "Free Drink Item",
    "Value EGP",
    "Staff",
    "Notes",
  ],
  "Unpaid Tracker": [
    "Customer ID",
    "Customer Name",
    "Phone",
    "Unpaid Balance",
    "Last Visit",
    "Open Unpaid Orders",
    "Action",
    "Promise Date",
    "Notes",
    "lastUnpaidDate",
  ],
  Menu: [
    "Item ID",
    "Category",
    "Item Name",
    "Flavor / Notes",
    "Price Text (edit later)",
    "Active",
    "Loyalty Eligible",
    "price",
  ],
  Payments: [
    "Payment Date",
    "Customer ID",
    "Customer Name",
    "Method",
    "Amount",
    "Collected By",
    "Related Order/Notes",
    "paymentId",
    "orderId",
    "receiptNumber",
    "businessDate",
    "customerNameSnapshot",
    "amountReceived",
    "amountApplied",
    "changeAmount",
    "paymentMethod",
    "paymentType",
    "receivedByUid",
    "receivedByName",
    "createdAt",
    "notes",
  ],
  Lists: [
    "Payment Status",
    "Order Status",
    "Staff",
    "Payment Method",
    "listType",
    "value",
    "active",
  ],
  "Day History": [
    "dateKey",
    "receiptCount",
    "orderCount",
    "paymentCount",
    "redemptionCount",
    "totalSales",
    "totalPaid",
    "totalUnpaid",
    "bestSellingItem",
    "bestSellingQty",
    "latestReceiptSerial",
    "resetAt",
    "resetBy",
  ],
  "Order Items": [
    "orderItemId",
    "orderId",
    "menuItemId",
    "menuItemName",
    "category",
    "size",
    "quantity",
    "unitPrice",
    "extrasTotal",
    "lineTotal",
    "notes",
    "preparationStatus",
    "discount",
    "menuItemNameSnapshot",
    "itemNotes",
    "createdAt",
    "updatedAt",
  ],
  "Audit Log": [
    "auditId",
    "userId",
    "role",
    "action",
    "entityType",
    "entityId",
    "previousValue",
    "newValue",
    "reason",
    "requestId",
    "success",
    "timestamp",
    "sessionMetadata",
  ],
  "Sync Failures": [
    "syncFailureId",
    "syncJobId",
    "entityType",
    "entityId",
    "errorMessage",
    "retryCount",
    "createdAt",
    "resolvedAt",
  ],
  "Customer Summary": [
    "customerId",
    "fullName",
    "phone",
    "active",
    "totalReceipts",
    "totalItems",
    "totalSales",
    "totalPaid",
    "unpaidBalance",
    "paidDrinkCount",
    "pointsEarned",
    "pointsRedeemed",
    "availablePoints",
    "freeDrinksEarned",
    "freeDrinksRedeemed",
    "freeDrinksReady",
    "firstVisit",
    "lastVisit",
    "averageReceipt",
    "favoritePurchasedItem",
    "customerStatus",
  ],
  "Daily Receipt Files": [
    "dailyFileId",
    "businessDate",
    "archiveBatchId",
    "fileName",
    "storageProvider",
    "storagePath",
    "downloadUrl",
    "receiptCount",
    "orderItemCount",
    "totalSales",
    "totalPaid",
    "totalRemaining",
    "cashTotal",
    "visaTotal",
    "walletTotal",
    "generatedAt",
    "generatedByUid",
    "generatedByName",
    "generationType",
    "archiveStatus",
    "version",
    "notes",
  ],
  "Business Settings": ["settingKey", "settingValue", "description"],
  "Schema Status": [
    "sheetName",
    "exists",
    "requiredHeaders",
    "missingHeaders",
    "duplicateHeaders",
    "rowCount",
    "lastCheckedAt",
    "status",
  ],
};

export const NORMALIZED_OPERATIONAL_SHEETS: NormalizedSheetName[] = [
  "Staff",
  "Customers",
  "Orders",
  "Menu",
  "Payments",
  "Day History",
  "Order Items",
  "Generated Vouchers",
  "Reward Redemptions",
  "Audit Log",
  "Sync Failures",
  "Customer Summary",
  "Daily Receipt Files",
  "Business Settings",
  "Schema Status",
];

export const SYSTEM_MANAGED_CUSTOMER_COLUMNS = new Set([
  "Total Orders",
  "Total Spent",
  "Paid Amount",
  "Unpaid Balance",
  "Points",
  "Free Drinks",
  "Last Visit",
  "Current Balance",
  "Paid Drinks",
  "Free Drinks Ready",
  "Last Visit Auto",
]);
