export type NormalizedSheetName =
  | "Dashboard"
  | "Menu Categories"
  | "Menu Items"
  | "Menu Item Sizes"
  | "Menu Item Flavors"
  | "Extras"
  | "Customers"
  | "Orders"
  | "Order Items"
  | "Order Item Extras"
  | "Payments"
  | "Unpaid Tracker"
  | "Rewards"
  | "Loyalty Winners"
  | "Reward Redemptions"
  | "Staff"
  | "Lists"
  | "Business Settings"
  | "Day History"
  | "Audit Log"
  | "Sync Failures"
  | "Migration Exceptions";

export const NORMALIZED_SHEETS: Record<string, NormalizedSheetName> = {
  auditLog: "Audit Log",
  businessSettings: "Business Settings",
  customers: "Customers",
  dashboard: "Dashboard",
  dayHistory: "Day History",
  extras: "Extras",
  lists: "Lists",
  loyaltyWinners: "Loyalty Winners",
  menuCategories: "Menu Categories",
  menuItemExtras: "Order Item Extras",
  menuItemFlavors: "Menu Item Flavors",
  menuItemSizes: "Menu Item Sizes",
  menuItems: "Menu Items",
  migrationExceptions: "Migration Exceptions",
  orderItems: "Order Items",
  orders: "Orders",
  payments: "Payments",
  redemption: "Reward Redemptions",
  rewards: "Rewards",
  staff: "Staff",
  syncFailures: "Sync Failures",
  unpaidTracker: "Unpaid Tracker",
} as const;

export const NORMALIZED_SHEET_HEADERS: Record<NormalizedSheetName, string[]> = {
  "Audit Log": [
    "Audit ID",
    "Request ID",
    "User ID",
    "User Role",
    "Action",
    "Entity Type",
    "Entity ID",
    "Previous Value JSON",
    "New Value JSON",
    "Reason",
    "Result",
    "Created At",
  ],
  "Business Settings": [
    "Setting Key",
    "Setting Value",
    "Value Type",
    "Description",
    "Updated By",
    "Updated At",
  ],
  Customers: [
    "Customer ID",
    "Full Name",
    "Phone",
    "WhatsApp",
    "Email",
    "Birthday",
    "Join Date",
    "Favorite Drink Item ID",
    "Notes",
    "Status",
    "Lifetime Orders",
    "Lifetime Spend EGP",
    "Lifetime Paid EGP",
    "Unpaid Balance EGP",
    "Loyalty Points",
    "Paid Drinks",
    "Free Drinks Available",
    "Last Visit At",
    "Created At",
    "Updated At",
    "Version",
  ],
  Dashboard: ["Metric", "Value", "Description", "Updated At"],
  "Day History": [
    "Business Day ID",
    "Business Date",
    "Opened At",
    "Closed At",
    "Closed By",
    "Order Count",
    "Gross Sales EGP",
    "Discount EGP",
    "Net Sales EGP",
    "Paid EGP",
    "Unpaid EGP",
    "Cash EGP",
    "Card EGP",
    "Wallet EGP",
    "Rewards Earned",
    "Rewards Redeemed",
    "Archive Status",
    "Archive Checksum",
    "Created At",
  ],
  Extras: [
    "Extra ID",
    "Extra Name",
    "Price EGP",
    "Active",
    "Display Order",
    "Created At",
    "Updated At",
  ],
  Lists: ["List Type", "Value", "Active"],
  "Loyalty Winners": [
    "Winner ID",
    "Customer ID",
    "Reward Type",
    "Reward Name",
    "Qualification Reason",
    "Status",
    "Qualified At",
    "Redeemed At",
    "Expired At",
    "Created At",
    "Updated At",
  ],
  "Menu Categories": [
    "Category ID",
    "Category Name",
    "Display Order",
    "Active",
    "Created At",
    "Updated At",
  ],
  "Menu Item Flavors": [
    "Flavor ID",
    "Item ID",
    "Flavor Name",
    "Price Adjustment EGP",
    "Active",
    "Display Order",
  ],
  "Menu Item Sizes": [
    "Size ID",
    "Item ID",
    "Size Name",
    "Price EGP",
    "Is Default",
    "Active",
    "Display Order",
    "Created At",
    "Updated At",
  ],
  "Menu Items": [
    "Item ID",
    "Category ID",
    "Item Name",
    "Description",
    "Ingredients",
    "Preparation Station",
    "Loyalty Eligible",
    "Active",
    "Sold Out",
    "Display Order",
    "Created At",
    "Updated At",
  ],
  "Migration Exceptions": [
    "Exception ID",
    "Migration Version",
    "Source Sheet",
    "Source Row",
    "Problem",
    "Suggested Correction",
    "Migration Status",
    "Created At",
  ],
  "Order Item Extras": [
    "Order Item Extra ID",
    "Order Item ID",
    "Order ID",
    "Extra ID",
    "Extra Name Snapshot",
    "Quantity",
    "Unit Price EGP",
    "Total EGP",
    "Created At",
  ],
  "Order Items": [
    "Order Item ID",
    "Order ID",
    "Menu Item ID",
    "Item Name Snapshot",
    "Category ID",
    "Size ID",
    "Size Name Snapshot",
    "Quantity",
    "Unit Price EGP",
    "Flavor ID",
    "Flavor Name Snapshot",
    "Extras Total EGP",
    "Line Discount EGP",
    "Line Total EGP",
    "Notes",
    "Preparation Station",
    "Preparation Status",
    "Created At",
    "Updated At",
    "Version",
  ],
  Orders: [
    "Order ID",
    "Receipt Number",
    "Business Date",
    "Created At",
    "Updated At",
    "Customer ID",
    "Waiter User ID",
    "Cashier User ID",
    "Order Type",
    "Table Number",
    "Status",
    "Payment Status",
    "Subtotal EGP",
    "Discount EGP",
    "Tax EGP",
    "Total EGP",
    "Paid Amount EGP",
    "Unpaid Amount EGP",
    "Notes",
    "Submitted At",
    "Closed At",
    "Cancelled At",
    "Archived At",
    "Idempotency Key",
    "Version",
  ],
  Payments: [
    "Payment ID",
    "Order ID",
    "Receipt Number",
    "Customer ID",
    "Payment Date",
    "Amount EGP",
    "Payment Method",
    "Payment Status",
    "Collected By User ID",
    "Transaction Reference",
    "Notes",
    "Reversal Of Payment ID",
    "Created At",
    "Updated At",
    "Idempotency Key",
  ],
  "Reward Redemptions": [
    "Redemption ID",
    "Winner ID",
    "Customer ID",
    "Order ID",
    "Reward Name",
    "Menu Item ID",
    "Value EGP",
    "Redeemed By User ID",
    "Redeemed At",
    "Status",
    "Notes",
    "Created At",
  ],
  Rewards: [
    "Reward Transaction ID",
    "Customer ID",
    "Order ID",
    "Transaction Type",
    "Points Added",
    "Points Removed",
    "Paid Drinks Added",
    "Free Drinks Added",
    "Free Drinks Removed",
    "Balance After",
    "Reason",
    "Created By User ID",
    "Created At",
  ],
  Staff: [
    "User ID",
    "Email",
    "Display Name",
    "Role",
    "Active",
    "Permissions Summary",
    "Created At",
    "Updated At",
    "Last Login At",
  ],
  "Sync Failures": [
    "Sync Failure ID",
    "Request ID",
    "Entity Type",
    "Entity ID",
    "Operation",
    "Target",
    "Error Code",
    "Error Message",
    "Retry Count",
    "Status",
    "First Failed At",
    "Last Retried At",
    "Resolved At",
  ],
  "Unpaid Tracker": [
    "Unpaid ID",
    "Order ID",
    "Receipt Number",
    "Customer ID",
    "Original Amount EGP",
    "Paid Toward Debt EGP",
    "Remaining Amount EGP",
    "Status",
    "Promise Date",
    "Last Payment Date",
    "Created At",
    "Updated At",
    "Closed At",
    "Notes",
    "Version",
  ],
};

export const NORMALIZED_OPERATIONAL_SHEETS = Object.keys(
  NORMALIZED_SHEET_HEADERS,
) as NormalizedSheetName[];

export const SYSTEM_MANAGED_CUSTOMER_COLUMNS = new Set([
  "Lifetime Orders",
  "Lifetime Spend EGP",
  "Lifetime Paid EGP",
  "Unpaid Balance EGP",
  "Loyalty Points",
  "Paid Drinks",
  "Free Drinks Available",
  "Last Visit At",
  "Version",
]);
