export const CANONICAL_SHEET_TABS = [
  "Dashboard",
  "Settings",
  "Staff",
  "Menu",
  "Customers",
  "Orders",
  "Order Items",
  "Payments",
  "Loyalty",
  "System Log",
] as const;

export type CanonicalSheetName = (typeof CANONICAL_SHEET_TABS)[number];
export type NormalizedSheetName = CanonicalSheetName;

export const NORMALIZED_SHEETS = {
  auditLog: "System Log",
  businessSettings: "Settings",
  customerSummary: "Customers",
  customers: "Customers",
  dailyReceiptFiles: "System Log",
  dashboard: "Dashboard",
  dayHistory: "System Log",
  generatedVouchers: "Loyalty",
  loyalty: "Loyalty",
  menu: "Menu",
  orderItems: "Order Items",
  orders: "Orders",
  payments: "Payments",
  redemption: "Loyalty",
  schemaStatus: "Settings",
  settings: "Settings",
  staff: "Staff",
  syncFailures: "System Log",
  systemLog: "System Log",
} as const satisfies Record<string, CanonicalSheetName>;

export const NORMALIZED_SHEET_HEADERS: Record<CanonicalSheetName, string[]> = {
  Dashboard: ["metric", "value", "category", "description", "lastRefreshed"],
  Settings: [
    "settingKey",
    "settingValue",
    "valueType",
    "category",
    "description",
    "active",
    "updatedAt",
    "updatedByUid",
    "updatedByName",
  ],
  Staff: [
    "uid",
    "email",
    "displayName",
    "role",
    "active",
    "permissionsJson",
    "revokedPermissionsJson",
    "createdAt",
    "updatedAt",
    "updatedByUid",
    "updatedByName",
  ],
  Menu: [
    "itemId",
    "categoryId",
    "categoryName",
    "itemName",
    "description",
    "flavorNotes",
    "imageUrl",
    "priceText",
    "sizesJson",
    "extrasJson",
    "standardSizeId",
    "preparationStation",
    "loyaltyEligible",
    "active",
    "soldOut",
    "displayOrder",
    "createdAt",
    "updatedAt",
    "updatedByUid",
    "updatedByName",
  ],
  Customers: [
    "customerId",
    "firebaseUid",
    "fullName",
    "phone",
    "email",
    "birthday",
    "favoriteDrink",
    "notes",
    "active",
    "joinDate",
    "firstVisit",
    "lastVisit",
    "totalOrders",
    "totalItems",
    "totalSales",
    "totalPaid",
    "unpaidBalance",
    "eligiblePaidDrinks",
    "freeDrinksEarned",
    "freeDrinksReserved",
    "freeDrinksRedeemed",
    "freeDrinksReady",
    "createdAt",
    "updatedAt",
  ],
  Orders: [
    "orderId",
    "receiptNumber",
    "clientRequestId",
    "deviceId",
    "businessDate",
    "createdAt",
    "updatedAt",
    "customerId",
    "customerUid",
    "customerNameSnapshot",
    "customerPhoneSnapshot",
    "createdByUid",
    "createdByName",
    "createdByRole",
    "serviceType",
    "orderPlace",
    "customerNotes",
    "itemCount",
    "itemSummary",
    "categorySummary",
    "subtotal",
    "itemDiscountTotal",
    "orderDiscount",
    "rewardDiscount",
    "discountTotal",
    "tax",
    "serviceCharge",
    "total",
    "amountReceived",
    "amountApplied",
    "paidAmount",
    "outstandingAmount",
    "changeAmount",
    "paymentMethod",
    "paymentStatus",
    "orderStatus",
    "activeBoard",
    "archived",
    "archivedAt",
    "archiveBatchId",
    "offlineCreated",
    "offlineCreatedAt",
    "syncStatus",
    "syncedAt",
    "legacyMigrationStatus",
  ],
  "Order Items": [
    "orderItemId",
    "orderId",
    "clientRequestId",
    "menuItemId",
    "menuItemNameSnapshot",
    "categoryId",
    "categoryNameSnapshot",
    "sizeId",
    "sizeName",
    "quantity",
    "trustedUnitPrice",
    "extrasJson",
    "extrasTotal",
    "discount",
    "lineTotal",
    "itemNotes",
    "preparationStation",
    "preparationStatus",
    "acceptedAt",
    "preparingAt",
    "readyAt",
    "pickedUpAt",
    "completedAt",
    "createdAt",
    "updatedAt",
  ],
  Payments: [
    "paymentId",
    "orderId",
    "receiptNumber",
    "clientRequestId",
    "businessDate",
    "customerId",
    "customerNameSnapshot",
    "paymentType",
    "paymentMethod",
    "amountReceived",
    "amountApplied",
    "changeAmount",
    "status",
    "receivedByUid",
    "receivedByName",
    "receivedByRole",
    "notes",
    "offlineCreated",
    "syncStatus",
    "createdAt",
    "syncedAt",
  ],
  Loyalty: [
    "loyaltyRecordId",
    "recordType",
    "customerId",
    "customerNameSnapshot",
    "relatedOrderId",
    "relatedVoucherCode",
    "sequenceNumber",
    "quantity",
    "points",
    "rewardType",
    "rewardItemId",
    "rewardItemName",
    "status",
    "reservedAt",
    "redeemedAt",
    "cancelledAt",
    "expiresAt",
    "createdByUid",
    "createdByName",
    "notes",
    "createdAt",
    "updatedAt",
  ],
  "System Log": [
    "logId",
    "eventType",
    "severity",
    "businessDate",
    "entityType",
    "entityId",
    "action",
    "actorUid",
    "actorName",
    "actorRole",
    "requestId",
    "clientRequestId",
    "previousValueJson",
    "newValueJson",
    "reason",
    "success",
    "errorCode",
    "errorMessage",
    "retryCount",
    "receiptFileId",
    "archiveBatchId",
    "sessionMetadataJson",
    "createdAt",
    "resolvedAt",
  ],
};

export const NORMALIZED_OPERATIONAL_SHEETS = [...CANONICAL_SHEET_TABS];
export const LIVE_SHEET_TABS = CANONICAL_SHEET_TABS;

export const LEGACY_SOURCE_TABS = [
  "Staff",
  "Dashboard",
  "Customers",
  "Orders",
  "Rewards",
  "Loyalty Winners",
  "Generated Vouchers",
  "Reward Redemptions",
  "Unpaid Tracker",
  "Menu",
  "Payments",
  "Lists",
  "Day History",
  "Order Items",
  "Audit Log",
  "Sync Failures",
  "Customer Summary",
  "Daily Receipt Files",
  "Business Settings",
  "Schema Status",
] as const;

export const SYSTEM_MANAGED_CUSTOMER_COLUMNS = new Set([
  "firstVisit",
  "lastVisit",
  "totalOrders",
  "totalItems",
  "totalSales",
  "totalPaid",
  "unpaidBalance",
  "eligiblePaidDrinks",
  "freeDrinksEarned",
  "freeDrinksReserved",
  "freeDrinksRedeemed",
  "freeDrinksReady",
  "createdAt",
  "updatedAt",
]);
