export type SheetSchema = {
  dateColumns?: string[];
  editableColumns: string[];
  formulaColumns?: string[];
  idColumns?: string[];
  requiredHeaders: string[];
  sheetName: string;
};

export const SHEET_SCHEMAS: Record<string, SheetSchema> = {
  customers: {
    sheetName: "Customers",
    requiredHeaders: [
      "customerId",
      "fullName",
      "phoneWhatsApp",
      "joinDate",
      "favoriteDrink",
      "active",
    ],
    editableColumns: [
      "customerId",
      "fullName",
      "phoneWhatsApp",
      "joinDate",
      "birthday",
      "favoriteDrink",
      "notes",
      "active",
    ],
    formulaColumns: [
      "totalOrders",
      "totalSpent",
      "paidAmount",
      "unpaidBalance",
      "points",
      "freeDrinks",
      "lastVisit",
      "currentBalance",
      "paidDrinks",
      "freeDrinksReady",
      "lastVisitAuto",
    ],
    idColumns: ["customerId"],
    dateColumns: ["joinDate", "birthday", "lastVisit", "lastVisitAuto"],
  },
  orders: {
    sheetName: "Orders",
    requiredHeaders: [
      "orderDateTime",
      "customerId",
      "customerName",
      "staff",
      "category",
      "item",
      "qty",
      "unitPrice",
      "discount",
      "total",
      "paymentStatus",
      "orderStatus",
      "notes",
    ],
    editableColumns: [
      "orderDateTime",
      "customerId",
      "customerName",
      "staff",
      "category",
      "item",
      "qty",
      "unitPrice",
      "discount",
      "total",
      "pointsEarned",
      "pointsRedeemed",
      "paymentStatus",
      "orderStatus",
      "notes",
    ],
    idColumns: ["orderId", "receiptSerial"],
    dateColumns: ["orderDateTime", "dateKey"],
  },
  payments: {
    sheetName: "Payments",
    requiredHeaders: [
      "paymentDate",
      "customerId",
      "customerName",
      "method",
      "amount",
      "collectedBy",
      "relatedOrderNotes",
    ],
    editableColumns: [
      "paymentDate",
      "customerId",
      "customerName",
      "method",
      "amount",
      "collectedBy",
      "relatedOrderNotes",
    ],
    idColumns: ["paymentId", "receiptSerial"],
    dateColumns: ["paymentDate", "dateKey"],
  },
  generatedVouchers: {
    sheetName: "Generated Vouchers",
    requiredHeaders: ["voucherCode", "customerId", "customerName", "redeemStatus"],
    editableColumns: [
      "voucherCode",
      "customerId",
      "customerName",
      "fullName",
      "phone",
      "phoneWhatsApp",
      "favoriteDrink",
      "voucherTitle",
      "voucherSubtitle",
      "voucherText",
      "voucherReward",
      "redeemStatus",
      "generatedAt",
      "createdAt",
      "date",
      "canvaStatus",
      "canvaLink",
    ],
    idColumns: ["voucherCode"],
    dateColumns: ["generatedAt", "createdAt", "date"],
  },
  rewardRedemptions: {
    sheetName: "Reward Redemptions",
    requiredHeaders: [
      "redemptionId",
      "date",
      "customerId",
      "customerName",
      "freeDrinkItem",
      "staff",
    ],
    editableColumns: [
      "redemptionId",
      "date",
      "customerId",
      "customerName",
      "freeDrinkItem",
      "valueEgp",
      "staff",
      "notes",
    ],
    idColumns: ["redemptionId"],
    dateColumns: ["date"],
  },
};

export function schemaForSheet(sheetName: string) {
  return Object.values(SHEET_SCHEMAS).find((schema) => schema.sheetName === sheetName);
}
