export type SheetSchema = {
  aliases?: Record<string, string[]>;
  calculatedColumns?: string[];
  dateColumns?: string[];
  editableColumns: string[];
  frontendWritableColumns?: string[];
  formulaColumns?: string[];
  idColumns?: string[];
  legacyIgnoredColumns?: string[];
  protectedColumns?: string[];
  requiredHeaders: string[];
  sheetName: string;
};

const identityAliases = (headers: string[]) =>
  Object.fromEntries(
    headers.map((header) => [normalizeSheetHeader(header), [header]]),
  );

const orderHeaders = [
  "Order Date/Time",
  "Customer ID",
  "Customer Name",
  "Staff",
  "Category",
  "Item",
  "Qty",
  "Unit Price",
  "Discount",
  "Total",
  "Points Earned",
  "Points Redeemed",
  "Payment Status",
  "Order Status",
  "Notes",
  "orderId",
  "receiptNumber",
  "businessDate",
  "customerPhone",
  "serviceType",
  "orderPlace",
  "itemCount",
  "itemSummary",
  "itemsJson",
  "categorySummary",
  "subtotal",
  "itemDiscountTotal",
  "orderDiscount",
  "paidAmount",
  "remainingAmount",
  "outstandingAmount",
  "changeAmount",
  "paymentMethod",
  "clientRequestId",
  "createdAt",
  "customerNameSnapshot",
  "customerPhoneSnapshot",
  "staffUid",
  "staffName",
  "staffRole",
  "serviceTypeMigrationDuplicate",
  "orderPlaceMigrationDuplicate",
  "discountTotal",
  "rewardDiscount",
  "tax",
  "serviceCharge",
  "amountReceived",
  "customerNotes",
  "activeBoard",
  "archived",
  "archivedAt",
  "archiveBatchId",
  "dailyPdfId",
  "createdByUid",
  "createdByEmail",
  "updatedAt",
  "amountApplied",
];

export const SHEET_SCHEMAS: Record<string, SheetSchema> = {
  staff: {
    sheetName: "Staff",
    requiredHeaders: [
      "Email",
      "Role",
      "Name",
      "Active",
      "displayName",
      "uid",
      "grant",
      "revoke",
      "updatedAt",
    ],
    editableColumns: [
      "email",
      "role",
      "name",
      "active",
      "displayName",
      "uid",
      "grant",
      "revoke",
      "updatedAt",
    ],
    frontendWritableColumns: [
      "email",
      "role",
      "name",
      "active",
      "displayName",
      "grant",
      "revoke",
    ],
    protectedColumns: ["uid", "updatedAt", "password"],
    legacyIgnoredColumns: ["Password"],
    idColumns: ["uid", "email"],
    dateColumns: ["updatedAt"],
    aliases: {
      ...identityAliases([
        "Email",
        "Role",
        "Name",
        "Active",
        "displayName",
        "uid",
        "grant",
        "revoke",
        "updatedAt",
      ]),
      displayName: ["Name", "displayName"],
    },
  },
  customers: {
    sheetName: "Customers",
    requiredHeaders: [
      "Customer ID",
      "Full Name",
      "Phone/WhatsApp",
      "Join Date",
      "Active?",
      "phone",
      "email",
      "createdAt",
      "updatedAt",
    ],
    editableColumns: [
      "customerId",
      "fullName",
      "phoneWhatsApp",
      "joinDate",
      "birthday",
      "favoriteDrink",
      "notes",
      "active",
      "phone",
      "email",
      "createdAt",
      "updatedAt",
    ],
    frontendWritableColumns: [
      "fullName",
      "phoneWhatsApp",
      "birthday",
      "favoriteDrink",
      "notes",
      "email",
    ],
    calculatedColumns: [
      "totalOrders",
      "totalSpent",
      "paidAmount",
      "unpaidBalance",
      "points",
      "freeDrinks",
      "lastVisit",
      "currentBalance",
      "paidDrinks",
      "freeDrinksReady",
      "lastVisitAuto",
    ],
    protectedColumns: [
      "customerId",
      "joinDate",
      "createdAt",
      "updatedAt",
      "totalOrders",
      "totalSpent",
      "paidAmount",
      "unpaidBalance",
      "points",
      "freeDrinks",
      "paidDrinks",
      "freeDrinksReady",
    ],
    idColumns: ["customerId"],
    dateColumns: [
      "joinDate",
      "birthday",
      "lastVisit",
      "lastVisitAuto",
      "createdAt",
      "updatedAt",
    ],
    aliases: {
      ...identityAliases([
        "Customer ID",
        "Full Name",
        "Phone/WhatsApp",
        "Join Date",
        "Birthday",
        "Favorite Drink",
        "Notes",
        "Active?",
        "Total Orders",
        "Total Spent",
        "Paid Amount",
        "Unpaid Balance",
        "Points",
        "Free Drinks",
        "Last Visit",
        "Current Balance",
        "Paid Drinks",
        "Free Drinks Ready",
        "Last Visit Auto",
        "phone",
        "email",
        "createdAt",
        "updatedAt",
      ]),
      phoneWhatsApp: ["Phone/WhatsApp", "phone", "Phone", "WhatsApp"],
    },
  },
  orders: {
    sheetName: "Orders",
    requiredHeaders: orderHeaders,
    editableColumns: orderHeaders.map(normalizeSheetHeader),
    frontendWritableColumns: [
      "customerId",
      "serviceType",
      "orderPlace",
      "customerNotes",
    ],
    calculatedColumns: [
      "itemCount",
      "itemSummary",
      "itemsJson",
      "categorySummary",
      "subtotal",
      "itemDiscountTotal",
      "discountTotal",
      "total",
      "paidAmount",
      "remainingAmount",
      "outstandingAmount",
      "changeAmount",
      "amountApplied",
      "paymentStatus",
      "pointsEarned",
      "pointsRedeemed",
    ],
    protectedColumns: [
      "orderId",
      "receiptNumber",
      "businessDate",
      "orderDateTime",
      "unitPrice",
      "subtotal",
      "itemDiscountTotal",
      "discountTotal",
      "rewardDiscount",
      "tax",
      "serviceCharge",
      "total",
      "paidAmount",
      "remainingAmount",
      "outstandingAmount",
      "changeAmount",
      "amountApplied",
      "paymentStatus",
      "orderStatus",
      "pointsEarned",
      "pointsRedeemed",
      "staffUid",
      "staffName",
      "staffRole",
      "activeBoard",
      "archived",
      "archivedAt",
      "archiveBatchId",
      "dailyPdfId",
      "createdByUid",
      "createdByEmail",
      "createdAt",
      "updatedAt",
    ],
    legacyIgnoredColumns: [
      "serviceTypeMigrationDuplicate",
      "orderPlaceMigrationDuplicate",
    ],
    idColumns: ["orderId", "receiptNumber", "clientRequestId"],
    dateColumns: [
      "orderDateTime",
      "businessDate",
      "createdAt",
      "updatedAt",
      "archivedAt",
    ],
    aliases: {
      ...identityAliases(orderHeaders),
      orderDateTime: ["Order Date/Time", "orderDateTime"],
      customerId: ["Customer ID", "customerId"],
      customerName: ["Customer Name", "customerName", "customerNameSnapshot"],
    },
  },
  orderItems: {
    sheetName: "Order Items",
    requiredHeaders: [
      "orderItemId",
      "orderId",
      "menuItemId",
      "menuItemName",
      "category",
      "size",
      "quantity",
      "unitPrice",
      "extrasTotal",
      "lineTotal",
      "notes",
      "preparationStatus",
      "discount",
      "menuItemNameSnapshot",
      "itemNotes",
      "createdAt",
      "updatedAt",
    ],
    editableColumns: [
      "orderItemId",
      "orderId",
      "menuItemId",
      "menuItemName",
      "category",
      "size",
      "quantity",
      "unitPrice",
      "extrasTotal",
      "lineTotal",
      "notes",
      "preparationStatus",
      "discount",
      "menuItemNameSnapshot",
      "itemNotes",
      "createdAt",
      "updatedAt",
    ],
    frontendWritableColumns: ["menuItemId", "size", "quantity", "itemNotes"],
    calculatedColumns: ["unitPrice", "extrasTotal", "discount", "lineTotal"],
    protectedColumns: [
      "orderItemId",
      "orderId",
      "menuItemNameSnapshot",
      "category",
      "unitPrice",
      "extrasTotal",
      "discount",
      "lineTotal",
      "preparationStatus",
      "createdAt",
      "updatedAt",
    ],
    idColumns: ["orderItemId", "orderId", "menuItemId"],
    dateColumns: ["createdAt", "updatedAt"],
    aliases: {
      ...identityAliases([
        "orderItemId",
        "orderId",
        "menuItemId",
        "menuItemName",
        "category",
        "size",
        "quantity",
        "unitPrice",
        "extrasTotal",
        "lineTotal",
        "notes",
        "preparationStatus",
        "discount",
        "menuItemNameSnapshot",
        "itemNotes",
        "createdAt",
        "updatedAt",
      ]),
      menuItemNameSnapshot: ["menuItemNameSnapshot", "menuItemName"],
    },
  },
  payments: {
    sheetName: "Payments",
    requiredHeaders: [
      "Payment Date",
      "Customer ID",
      "Customer Name",
      "Method",
      "Amount",
      "Collected By",
      "Related Order/Notes",
      "paymentId",
      "orderId",
      "receiptNumber",
      "businessDate",
      "customerNameSnapshot",
      "amountReceived",
      "amountApplied",
      "changeAmount",
      "paymentMethod",
      "paymentType",
      "receivedByUid",
      "receivedByName",
      "createdAt",
      "notes",
    ],
    editableColumns: [
      "paymentDate",
      "customerId",
      "customerName",
      "method",
      "amount",
      "collectedBy",
      "relatedOrderNotes",
      "paymentId",
      "orderId",
      "receiptNumber",
      "businessDate",
      "customerNameSnapshot",
      "amountReceived",
      "amountApplied",
      "changeAmount",
      "paymentMethod",
      "paymentType",
      "receivedByUid",
      "receivedByName",
      "createdAt",
      "notes",
    ],
    frontendWritableColumns: [
      "orderId",
      "amountReceived",
      "paymentMethod",
      "notes",
    ],
    calculatedColumns: ["amountApplied", "changeAmount"],
    protectedColumns: [
      "paymentId",
      "customerId",
      "customerName",
      "amountApplied",
      "changeAmount",
      "receivedByUid",
      "receivedByName",
      "createdAt",
      "businessDate",
    ],
    idColumns: ["paymentId", "orderId", "receiptNumber"],
    dateColumns: ["paymentDate", "businessDate", "createdAt"],
    aliases: {
      ...identityAliases([
        "Payment Date",
        "Customer ID",
        "Customer Name",
        "Method",
        "Amount",
        "Collected By",
        "Related Order/Notes",
        "paymentId",
        "orderId",
        "receiptNumber",
        "businessDate",
        "customerNameSnapshot",
        "amountReceived",
        "amountApplied",
        "changeAmount",
        "paymentMethod",
        "paymentType",
        "receivedByUid",
        "receivedByName",
        "createdAt",
        "notes",
      ]),
      paymentMethod: ["paymentMethod", "Method"],
      amountReceived: ["amountReceived", "Amount"],
    },
  },
  menu: {
    sheetName: "Menu",
    requiredHeaders: [
      "Item ID",
      "Category",
      "Item Name",
      "Flavor / Notes",
      "Price Text (edit later)",
      "Active",
      "Loyalty Eligible",
      "price",
    ],
    editableColumns: [
      "itemId",
      "category",
      "itemName",
      "flavorNotes",
      "priceTextEditLater",
      "active",
      "loyaltyEligible",
      "price",
    ],
    frontendWritableColumns: [
      "category",
      "itemName",
      "flavorNotes",
      "priceTextEditLater",
      "active",
      "loyaltyEligible",
    ],
    protectedColumns: ["itemId"],
    idColumns: ["itemId"],
    aliases: {
      ...identityAliases([
        "Item ID",
        "Category",
        "Item Name",
        "Flavor / Notes",
        "Price Text (edit later)",
        "Active",
        "Loyalty Eligible",
        "price",
      ]),
      priceText: ["Price Text (edit later)", "price"],
    },
  },
  generatedVouchers: {
    sheetName: "Generated Vouchers",
    requiredHeaders: [
      "Voucher Code",
      "Customer ID",
      "Customer Name",
      "Phone",
      "Favorite Drink",
      "Voucher Title",
      "Voucher Subtitle",
      "Voucher Text",
      "Voucher Reward",
      "Redeem Status",
      "Generated At",
      "fullName",
      "phoneWhatsApp",
      "createdAt",
      "date",
    ],
    editableColumns: [
      "voucherCode",
      "customerId",
      "customerName",
      "phone",
      "favoriteDrink",
      "voucherTitle",
      "voucherSubtitle",
      "voucherText",
      "voucherReward",
      "redeemStatus",
      "generatedAt",
      "fullName",
      "phoneWhatsApp",
      "createdAt",
      "date",
    ],
    frontendWritableColumns: [],
    protectedColumns: [
      "voucherCode",
      "customerId",
      "customerName",
      "redeemStatus",
      "generatedAt",
      "createdAt",
    ],
    idColumns: ["voucherCode"],
    dateColumns: ["generatedAt", "createdAt", "date"],
    aliases: {
      ...identityAliases([
        "Voucher Code",
        "Customer ID",
        "Customer Name",
        "Phone",
        "Favorite Drink",
        "Voucher Title",
        "Voucher Subtitle",
        "Voucher Text",
        "Voucher Reward",
        "Redeem Status",
        "Generated At",
        "fullName",
        "phoneWhatsApp",
        "createdAt",
        "date",
      ]),
      voucherCode: ["Voucher Code", "voucherCode", "code"],
    },
  },
  rewardRedemptions: schema(
    "Reward Redemptions",
    [
      "Redemption ID",
      "Date",
      "Customer ID",
      "Customer Name",
      "Free Drink Item",
      "Value EGP",
      "Staff",
      "Notes",
    ],
    ["redemptionId", "customerId"],
    ["date"],
  ),
  auditLog: schema(
    "Audit Log",
    [
      "auditId",
      "userId",
      "role",
      "action",
      "entityType",
      "entityId",
      "previousValue",
      "newValue",
      "reason",
      "requestId",
      "success",
      "timestamp",
      "sessionMetadata",
    ],
    ["auditId"],
    ["timestamp"],
  ),
  syncFailures: schema(
    "Sync Failures",
    [
      "syncFailureId",
      "syncJobId",
      "entityType",
      "entityId",
      "errorMessage",
      "retryCount",
      "createdAt",
      "resolvedAt",
    ],
    ["syncFailureId", "syncJobId"],
    ["createdAt", "resolvedAt"],
  ),
  customerSummary: schema(
    "Customer Summary",
    [
      "customerId",
      "fullName",
      "phone",
      "active",
      "totalReceipts",
      "totalItems",
      "totalSales",
      "totalPaid",
      "unpaidBalance",
      "paidDrinkCount",
      "pointsEarned",
      "pointsRedeemed",
      "availablePoints",
      "freeDrinksEarned",
      "freeDrinksRedeemed",
      "freeDrinksReady",
      "firstVisit",
      "lastVisit",
      "averageReceipt",
      "favoritePurchasedItem",
      "customerStatus",
    ],
    ["customerId"],
    ["firstVisit", "lastVisit"],
    true,
  ),
  dailyReceiptFiles: schema(
    "Daily Receipt Files",
    [
      "dailyFileId",
      "businessDate",
      "archiveBatchId",
      "fileName",
      "storageProvider",
      "storagePath",
      "downloadUrl",
      "receiptCount",
      "orderItemCount",
      "totalSales",
      "totalPaid",
      "totalRemaining",
      "cashTotal",
      "visaTotal",
      "walletTotal",
      "generatedAt",
      "generatedByUid",
      "generatedByName",
      "generationType",
      "archiveStatus",
      "version",
      "notes",
    ],
    ["dailyFileId", "archiveBatchId"],
    ["businessDate", "generatedAt"],
    true,
  ),
  businessSettings: schema(
    "Business Settings",
    ["settingKey", "settingValue", "description"],
    ["settingKey"],
    [],
  ),
  schemaStatus: schema(
    "Schema Status",
    [
      "sheetName",
      "exists",
      "requiredHeaders",
      "missingHeaders",
      "duplicateHeaders",
      "rowCount",
      "lastCheckedAt",
      "status",
    ],
    ["sheetName"],
    ["lastCheckedAt"],
    true,
  ),
  dayHistory: schema(
    "Day History",
    [
      "dateKey",
      "receiptCount",
      "orderCount",
      "paymentCount",
      "redemptionCount",
      "totalSales",
      "totalPaid",
      "totalUnpaid",
      "bestSellingItem",
      "bestSellingQty",
      "latestReceiptSerial",
      "resetAt",
      "resetBy",
    ],
    ["dateKey"],
    ["dateKey", "resetAt"],
    true,
  ),
};

function schema(
  sheetName: string,
  requiredHeaders: string[],
  idColumns: string[] = [],
  dateColumns: string[] = [],
  protectedOnly = false,
): SheetSchema {
  const normalized = requiredHeaders.map(normalizeSheetHeader);
  return {
    aliases: identityAliases(requiredHeaders),
    dateColumns,
    editableColumns: protectedOnly ? [] : normalized,
    frontendWritableColumns: [],
    idColumns,
    protectedColumns: protectedOnly ? normalized : idColumns,
    requiredHeaders,
    sheetName,
  };
}

export function normalizeSheetHeader(value: string) {
  return String(value || "")
    .trim()
    .replace(/[?]/g, "")
    .replace(/[^a-zA-Z0-9]+(.)/g, (_match, letter: string) =>
      letter.toUpperCase(),
    )
    .replace(/^[A-Z]/, (letter) => letter.toLowerCase());
}

export function schemaForSheet(sheetName: string) {
  return Object.values(SHEET_SCHEMAS).find(
    (entry) => entry.sheetName.toLowerCase() === sheetName.trim().toLowerCase(),
  );
}

export function resolveCanonicalHeader(sheetName: string, header: string) {
  const target = normalizeSheetHeader(header);
  const entry = schemaForSheet(sheetName);
  if (!entry) return target;
  for (const [canonical, aliases] of Object.entries(
    entry.aliases || {},
  ).reverse()) {
    if (
      [canonical, ...aliases].some(
        (alias) => normalizeSheetHeader(alias) === target,
      )
    )
      return canonical;
  }
  return target;
}
