export type SheetSchema = {
  dateColumns?: string[];
  editableColumns: string[];
  formulaColumns?: string[];
  idColumns?: string[];
  requiredHeaders: string[];
  sheetName: string;
};

export const SHEET_SCHEMAS: Record<string, SheetSchema> = {
  customers: {
    sheetName: "Customers",
    requiredHeaders: [
      "customerId",
      "fullName",
      "phoneWhatsApp",
      "joinDate",
      "favoriteDrink",
      "active",
    ],
    editableColumns: [
      "customerId",
      "fullName",
      "phoneWhatsApp",
      "joinDate",
      "birthday",
      "favoriteDrink",
      "notes",
      "active",
    ],
    formulaColumns: [
      "totalOrders",
      "totalSpent",
      "paidAmount",
      "unpaidBalance",
      "points",
      "freeDrinks",
      "lastVisit",
      "currentBalance",
      "paidDrinks",
      "freeDrinksReady",
      "lastVisitAuto",
    ],
    idColumns: ["customerId"],
    dateColumns: ["joinDate", "birthday", "lastVisit", "lastVisitAuto"],
  },
  orders: {
    sheetName: "Orders",
    requiredHeaders: [
      "orderId",
      "receiptNumber",
      "businessDate",
      "orderDateTime",
      "customerId",
      "customerName",
      "staff",
      "category",
      "item",
      "qty",
      "unitPrice",
      "discount",
      "total",
      "paymentStatus",
      "orderStatus",
      "notes",
    ],
    editableColumns: [
      "orderId",
      "receiptNumber",
      "businessDate",
      "orderDateTime",
      "customerId",
      "customerName",
      "staff",
      "category",
      "item",
      "qty",
      "unitPrice",
      "discount",
      "total",
      "paidAmount",
      "outstandingAmount",
      "remainingAmount",
      "changeAmount",
      "pointsEarned",
      "pointsRedeemed",
      "paymentStatus",
      "orderStatus",
      "notes",
    ],
    idColumns: ["orderId", "receiptNumber", "receiptSerial"],
    dateColumns: ["businessDate", "orderDateTime", "dateKey"],
  },
  orderItems: {
    sheetName: "Order Items",
    requiredHeaders: [
      "orderItemId",
      "orderId",
      "menuItemId",
      "menuItemName",
      "category",
      "size",
      "quantity",
      "unitPrice",
      "discount",
      "extrasTotal",
      "lineTotal",
      "preparationStatus",
    ],
    editableColumns: [
      "orderItemId",
      "orderId",
      "menuItemId",
      "menuItemName",
      "category",
      "size",
      "quantity",
      "unitPrice",
      "extrasTotal",
      "lineTotal",
      "notes",
      "preparationStatus",
    ],
    idColumns: ["orderItemId", "orderId"],
  },
  payments: {
    sheetName: "Payments",
    requiredHeaders: [
      "paymentId",
      "orderId",
      "paymentDate",
      "customerId",
      "customerName",
      "method",
      "amount",
      "collectedBy",
      "relatedOrderNotes",
    ],
    editableColumns: [
      "paymentId",
      "orderId",
      "paymentDate",
      "customerId",
      "customerName",
      "method",
      "amount",
      "collectedBy",
      "relatedOrderNotes",
    ],
    idColumns: ["paymentId", "orderId", "receiptSerial"],
    dateColumns: ["paymentDate", "dateKey"],
  },
  auditLog: {
    sheetName: "Audit Log",
    requiredHeaders: [
      "auditId",
      "userId",
      "role",
      "action",
      "entityType",
      "success",
      "timestamp",
    ],
    editableColumns: [
      "auditId",
      "userId",
      "role",
      "action",
      "entityType",
      "entityId",
      "previousValue",
      "newValue",
      "reason",
      "requestId",
      "success",
      "timestamp",
      "sessionMetadata",
    ],
    idColumns: ["auditId"],
    dateColumns: ["timestamp"],
  },
  syncFailures: {
    sheetName: "Sync Failures",
    requiredHeaders: [
      "syncFailureId",
      "entityType",
      "entityId",
      "errorMessage",
      "createdAt",
    ],
    editableColumns: [
      "syncFailureId",
      "syncJobId",
      "entityType",
      "entityId",
      "errorMessage",
      "retryCount",
      "createdAt",
      "resolvedAt",
    ],
    idColumns: ["syncFailureId", "syncJobId"],
    dateColumns: ["createdAt", "resolvedAt"],
  },
  generatedVouchers: {
    sheetName: "Generated Vouchers",
    requiredHeaders: [
      "voucherCode",
      "customerId",
      "customerName",
      "redeemStatus",
    ],
    editableColumns: [
      "voucherCode",
      "customerId",
      "customerName",
      "fullName",
      "phone",
      "phoneWhatsApp",
      "favoriteDrink",
      "voucherTitle",
      "voucherSubtitle",
      "voucherText",
      "voucherReward",
      "redeemStatus",
      "generatedAt",
      "createdAt",
      "date",
      "canvaStatus",
      "canvaLink",
    ],
    idColumns: ["voucherCode"],
    dateColumns: ["generatedAt", "createdAt", "date"],
  },
  rewardRedemptions: {
    sheetName: "Reward Redemptions",
    requiredHeaders: [
      "redemptionId",
      "date",
      "customerId",
      "customerName",
      "freeDrinkItem",
      "staff",
    ],
    editableColumns: [
      "redemptionId",
      "date",
      "customerId",
      "customerName",
      "freeDrinkItem",
      "valueEgp",
      "staff",
      "notes",
    ],
    idColumns: ["redemptionId"],
    dateColumns: ["date"],
  },
};

export function schemaForSheet(sheetName: string) {
  return Object.values(SHEET_SCHEMAS).find(
    (schema) => schema.sheetName === sheetName,
  );
}
