-- Joy Corner operational schema. Supabase PostgreSQL is the intended source of
-- truth after the dual-run migration described in docs/supabase-migration-plan.md.

create extension if not exists pgcrypto with schema extensions;
create extension if not exists citext with schema extensions;

do $$ begin
  create type public.app_role as enum ('owner', 'manager', 'cashier', 'waiter', 'barista', 'customer');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.order_status as enum (
    'draft', 'pending_confirmation', 'confirmed', 'accepted', 'preparing',
    'ready', 'picked_up', 'closed', 'rejected', 'cancelled'
  );
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.confirmation_status as enum ('not_required', 'pending', 'confirmed', 'rejected', 'cancelled');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.payment_status as enum ('unpaid', 'pending_verification', 'partially_paid', 'paid', 'refunded');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.order_source as enum ('customer_app', 'waiter', 'cashier', 'owner', 'migration');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.payment_method as enum ('cash_at_cashier', 'card_at_branch', 'instapay', 'manual_transfer');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.payment_record_status as enum ('pending', 'confirmed', 'rejected', 'refunded');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.voucher_status as enum ('active', 'reserved', 'redeemed', 'expired', 'cancelled');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.voucher_type as enum ('fixed', 'percentage', 'free_item', 'loyalty_free_drink');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.reward_transaction_type as enum ('earn', 'redeem', 'adjustment', 'migration');
exception when duplicate_object then null; end $$;

create sequence if not exists public.customer_number_seq start 1;
create sequence if not exists public.order_number_seq start 1;
create sequence if not exists public.payment_number_seq start 1;

create table if not exists public.roles (
  id bigint generated by default as identity primary key,
  name public.app_role not null unique,
  description text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.permissions (
  id bigint generated by default as identity primary key,
  permission_key text not null unique check (permission_key ~ '^[a-z][a-z0-9_.-]+$'),
  description text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  legacy_id text unique,
  customer_number text unique,
  full_name text not null check (char_length(trim(full_name)) between 2 and 160),
  phone text,
  email extensions.citext unique,
  role public.app_role not null default 'customer',
  active boolean not null default true,
  date_of_birth date,
  favorite_drink text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_login_at timestamptz,
  constraint profiles_customer_number_role check (
    (role = 'customer' and customer_number is not null)
    or (role <> 'customer')
  ),
  constraint profiles_phone_format check (phone is null or phone ~ '^\+?[0-9]{8,15}$')
);

create unique index if not exists profiles_phone_unique_idx
  on public.profiles (phone) where phone is not null;
create index if not exists profiles_role_active_idx on public.profiles (role, active);
create index if not exists profiles_created_at_idx on public.profiles (created_at desc);

create table if not exists public.role_permissions (
  role_id bigint not null references public.roles(id) on delete cascade,
  permission_id bigint not null references public.permissions(id) on delete cascade,
  enabled boolean not null default true,
  updated_at timestamptz not null default now(),
  primary key (role_id, permission_id)
);

create table if not exists public.user_permissions (
  user_id uuid not null references public.profiles(id) on delete cascade,
  permission_id bigint not null references public.permissions(id) on delete cascade,
  enabled boolean not null,
  granted_by uuid references public.profiles(id) on delete set null,
  updated_at timestamptz not null default now(),
  primary key (user_id, permission_id)
);

create table if not exists public.business_settings (
  setting_key text primary key,
  setting_value jsonb not null,
  description text not null default '',
  updated_at timestamptz not null default now(),
  updated_by uuid references public.profiles(id) on delete set null
);

create table if not exists public.menu_categories (
  id uuid primary key default extensions.gen_random_uuid(),
  legacy_id text unique,
  name text not null unique,
  description text not null default '',
  image_url text,
  sort_order integer not null default 0 check (sort_order >= 0),
  active boolean not null default true,
  archived_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists menu_categories_active_sort_idx
  on public.menu_categories (active, sort_order, name);

create table if not exists public.menu_items (
  id uuid primary key default extensions.gen_random_uuid(),
  legacy_id text unique,
  category_id uuid not null references public.menu_categories(id) on delete restrict,
  name text not null,
  description text not null default '',
  base_price numeric(12,2) not null default 0 check (base_price >= 0),
  image_url text,
  active boolean not null default true,
  available boolean not null default true,
  loyalty_eligible boolean not null default true,
  preparation_station text not null default 'barista'
    check (preparation_station in ('barista', 'kitchen')),
  sort_order integer not null default 0 check (sort_order >= 0),
  archived_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (category_id, name)
);

create index if not exists menu_items_category_active_idx
  on public.menu_items (category_id, active, available, sort_order);

create table if not exists public.menu_item_sizes (
  id uuid primary key default extensions.gen_random_uuid(),
  legacy_id text unique,
  menu_item_id uuid not null references public.menu_items(id) on delete cascade,
  size_name text not null,
  price numeric(12,2) not null check (price > 0),
  active boolean not null default true,
  sort_order integer not null default 0 check (sort_order >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (menu_item_id, size_name)
);

create index if not exists menu_item_sizes_item_active_idx
  on public.menu_item_sizes (menu_item_id, active, sort_order);

create table if not exists public.menu_modifiers (
  id uuid primary key default extensions.gen_random_uuid(),
  legacy_id text unique,
  name text not null unique,
  price numeric(12,2) not null default 0 check (price >= 0),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.menu_item_modifiers (
  menu_item_id uuid not null references public.menu_items(id) on delete cascade,
  modifier_id uuid not null references public.menu_modifiers(id) on delete cascade,
  primary key (menu_item_id, modifier_id)
);

create table if not exists public.vouchers (
  id uuid primary key default extensions.gen_random_uuid(),
  legacy_id text unique,
  voucher_code text not null unique,
  customer_id uuid not null references public.profiles(id) on delete restrict,
  voucher_type public.voucher_type not null,
  fixed_value numeric(12,2) check (fixed_value is null or fixed_value > 0),
  percentage_value numeric(5,2) check (percentage_value is null or percentage_value > 0 and percentage_value <= 100),
  free_item_id uuid references public.menu_items(id) on delete set null,
  status public.voucher_status not null default 'active',
  issued_at timestamptz not null default now(),
  expires_at timestamptz,
  redeemed_at timestamptz,
  redeemed_order_id uuid,
  created_by uuid references public.profiles(id) on delete set null,
  related_reward_transaction_id uuid,
  canva_design_url text,
  qr_token uuid not null default extensions.gen_random_uuid() unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint vouchers_value_shape check (
    (voucher_type = 'fixed' and fixed_value is not null)
    or (voucher_type = 'percentage' and percentage_value is not null)
    or (voucher_type in ('free_item', 'loyalty_free_drink') and free_item_id is not null)
  )
);

create index if not exists vouchers_customer_status_idx
  on public.vouchers (customer_id, status, expires_at);
create index if not exists vouchers_code_idx on public.vouchers (voucher_code);

create table if not exists public.orders (
  id uuid primary key default extensions.gen_random_uuid(),
  legacy_id text unique,
  order_number text not null unique,
  customer_id uuid references public.profiles(id) on delete restrict,
  pickup_name text not null,
  source public.order_source not null,
  status public.order_status not null default 'draft',
  confirmation_status public.confirmation_status not null default 'not_required',
  payment_status public.payment_status not null default 'unpaid',
  kitchen_visible boolean not null default false,
  subtotal numeric(12,2) not null default 0 check (subtotal >= 0),
  discount_total numeric(12,2) not null default 0 check (discount_total >= 0),
  voucher_discount numeric(12,2) not null default 0 check (voucher_discount >= 0),
  tax_total numeric(12,2) not null default 0 check (tax_total >= 0),
  total numeric(12,2) not null default 0 check (total >= 0),
  payment_method public.payment_method,
  requested_voucher_id uuid references public.vouchers(id) on delete set null,
  confirmed_by uuid references public.profiles(id) on delete set null,
  confirmed_at timestamptz,
  assigned_barista_id uuid references public.profiles(id) on delete set null,
  accepted_at timestamptz,
  preparing_at timestamptz,
  ready_at timestamptz,
  picked_up_at timestamptz,
  closed_at timestamptz,
  rejected_at timestamptz,
  rejection_reason text,
  cancelled_at timestamptz,
  cancellation_reason text,
  customer_notes text not null default '',
  idempotency_key text not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint orders_customer_source check (
    (source <> 'customer_app') or customer_id is not null
  ),
  constraint orders_customer_initial_state check (
    source <> 'customer_app'
    or status <> 'pending_confirmation'
    or (confirmation_status = 'pending' and kitchen_visible = false)
  ),
  constraint orders_total_math check (
    total = greatest(0, subtotal - discount_total - voucher_discount + tax_total)
  )
);

alter table public.vouchers
  drop constraint if exists vouchers_redeemed_order_id_fkey;
alter table public.vouchers
  add constraint vouchers_redeemed_order_id_fkey
  foreign key (redeemed_order_id) references public.orders(id) on delete set null;

create index if not exists orders_customer_created_idx
  on public.orders (customer_id, created_at desc);
create index if not exists orders_status_created_idx
  on public.orders (status, created_at desc);
create index if not exists orders_confirmation_created_idx
  on public.orders (confirmation_status, created_at desc);
create index if not exists orders_payment_created_idx
  on public.orders (payment_status, created_at desc);
create index if not exists orders_active_queue_idx
  on public.orders (created_at desc)
  where status not in ('closed', 'rejected', 'cancelled');

create table if not exists public.order_private_notes (
  order_id uuid primary key references public.orders(id) on delete cascade,
  internal_notes text not null default '',
  updated_at timestamptz not null default now(),
  updated_by uuid references public.profiles(id) on delete set null
);

create table if not exists public.order_items (
  id uuid primary key default extensions.gen_random_uuid(),
  legacy_id text unique,
  order_id uuid not null references public.orders(id) on delete cascade,
  menu_item_id uuid references public.menu_items(id) on delete set null,
  item_name_snapshot text not null,
  category_name_snapshot text not null,
  size_name text not null,
  quantity integer not null check (quantity > 0),
  unit_price numeric(12,2) not null check (unit_price >= 0),
  modifiers_total numeric(12,2) not null default 0 check (modifiers_total >= 0),
  total_price numeric(12,2) not null check (total_price >= 0),
  loyalty_eligible boolean not null default true,
  customer_notes text not null default '',
  preparation_notes text not null default '',
  created_at timestamptz not null default now(),
  constraint order_items_total_math check (
    total_price = quantity * (unit_price + modifiers_total)
  )
);

create index if not exists order_items_order_idx on public.order_items (order_id);
create index if not exists order_items_menu_item_idx on public.order_items (menu_item_id);

create table if not exists public.order_item_modifiers (
  id uuid primary key default extensions.gen_random_uuid(),
  order_item_id uuid not null references public.order_items(id) on delete cascade,
  modifier_id uuid references public.menu_modifiers(id) on delete set null,
  modifier_name_snapshot text not null,
  unit_price numeric(12,2) not null default 0 check (unit_price >= 0),
  quantity integer not null default 1 check (quantity > 0),
  total_price numeric(12,2) not null check (total_price >= 0),
  created_at timestamptz not null default now(),
  constraint order_item_modifiers_total_math check (total_price = unit_price * quantity)
);

create index if not exists order_item_modifiers_item_idx
  on public.order_item_modifiers (order_item_id);

create table if not exists public.payments (
  id uuid primary key default extensions.gen_random_uuid(),
  legacy_id text unique,
  payment_number text not null unique,
  order_id uuid not null references public.orders(id) on delete restrict,
  customer_id uuid references public.profiles(id) on delete restrict,
  amount numeric(12,2) not null check (amount > 0),
  payment_method public.payment_method not null,
  status public.payment_record_status not null default 'pending',
  reference text,
  proof_url text,
  confirmed_by uuid references public.profiles(id) on delete set null,
  confirmed_at timestamptz,
  idempotency_key text not null unique,
  created_at timestamptz not null default now()
);

create index if not exists payments_order_created_idx on public.payments (order_id, created_at desc);
create index if not exists payments_customer_created_idx on public.payments (customer_id, created_at desc);
create index if not exists payments_status_created_idx on public.payments (status, created_at desc);

create table if not exists public.rewards_accounts (
  customer_id uuid primary key references public.profiles(id) on delete cascade,
  points_balance integer not null default 0 check (points_balance >= 0),
  eligible_purchase_count integer not null default 0 check (eligible_purchase_count >= 0),
  free_rewards_available integer not null default 0 check (free_rewards_available >= 0),
  updated_at timestamptz not null default now()
);

create table if not exists public.reward_transactions (
  id uuid primary key default extensions.gen_random_uuid(),
  legacy_id text unique,
  customer_id uuid not null references public.profiles(id) on delete restrict,
  order_id uuid references public.orders(id) on delete restrict,
  transaction_type public.reward_transaction_type not null,
  points integer not null default 0,
  eligible_purchase_change integer not null default 0,
  free_reward_change integer not null default 0,
  description text not null,
  created_at timestamptz not null default now(),
  created_by uuid references public.profiles(id) on delete set null,
  idempotency_key text not null unique
);

create unique index if not exists reward_order_earn_unique_idx
  on public.reward_transactions (order_id, transaction_type)
  where order_id is not null and transaction_type = 'earn';
create index if not exists reward_transactions_customer_idx
  on public.reward_transactions (customer_id, created_at desc);

alter table public.vouchers
  drop constraint if exists vouchers_related_reward_transaction_id_fkey;
alter table public.vouchers
  add constraint vouchers_related_reward_transaction_id_fkey
  foreign key (related_reward_transaction_id)
  references public.reward_transactions(id) on delete set null;

create table if not exists public.voucher_redemptions (
  id uuid primary key default extensions.gen_random_uuid(),
  legacy_id text unique,
  voucher_id uuid not null unique references public.vouchers(id) on delete restrict,
  customer_id uuid not null references public.profiles(id) on delete restrict,
  order_id uuid not null references public.orders(id) on delete restrict,
  redeemed_by uuid not null references public.profiles(id) on delete restrict,
  redeemed_at timestamptz not null default now(),
  discount_amount numeric(12,2) not null check (discount_amount >= 0),
  idempotency_key text not null unique
);

create index if not exists voucher_redemptions_customer_idx
  on public.voucher_redemptions (customer_id, redeemed_at desc);

create table if not exists public.notifications (
  id uuid primary key default extensions.gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  type text not null,
  title text not null,
  message text not null,
  read boolean not null default false,
  related_order_id uuid references public.orders(id) on delete cascade,
  created_at timestamptz not null default now()
);

create index if not exists notifications_user_unread_idx
  on public.notifications (user_id, read, created_at desc);

create table if not exists public.order_status_history (
  id uuid primary key default extensions.gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  old_status public.order_status,
  new_status public.order_status not null,
  changed_by uuid references public.profiles(id) on delete set null,
  reason text,
  created_at timestamptz not null default now()
);

create index if not exists order_status_history_order_idx
  on public.order_status_history (order_id, created_at);

create table if not exists public.audit_logs (
  id uuid primary key default extensions.gen_random_uuid(),
  actor_user_id uuid references public.profiles(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id text,
  old_values jsonb,
  new_values jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists audit_logs_actor_idx on public.audit_logs (actor_user_id, created_at desc);
create index if not exists audit_logs_entity_idx on public.audit_logs (entity_type, entity_id, created_at desc);

create table if not exists public.operation_requests (
  actor_user_id uuid not null references public.profiles(id) on delete cascade,
  action text not null,
  idempotency_key text not null,
  response jsonb,
  created_at timestamptz not null default now(),
  primary key (actor_user_id, action, idempotency_key)
);

-- Realtime projection for cashiers. It intentionally excludes profile history,
-- private profile fields, rewards, and lifetime spending.
create table if not exists public.cashier_order_queue (
  order_id uuid primary key references public.orders(id) on delete cascade,
  order_number text not null,
  pickup_name text not null,
  status public.order_status not null,
  confirmation_status public.confirmation_status not null,
  payment_status public.payment_status not null,
  subtotal numeric(12,2) not null,
  discount_total numeric(12,2) not null,
  voucher_discount numeric(12,2) not null,
  tax_total numeric(12,2) not null,
  total numeric(12,2) not null,
  payment_method public.payment_method,
  requested_voucher_id uuid,
  customer_notes text not null default '',
  item_summary jsonb not null default '[]'::jsonb,
  created_at timestamptz not null,
  updated_at timestamptz not null
);

create index if not exists cashier_queue_pending_idx
  on public.cashier_order_queue (confirmation_status, created_at desc);

-- Realtime projection for baristas. No payment, voucher, phone, email, balance,
-- reward, or private customer fields exist in this relation.
create table if not exists public.kitchen_order_queue (
  order_id uuid primary key references public.orders(id) on delete cascade,
  order_number text not null,
  pickup_name text not null,
  status public.order_status not null,
  item_summary jsonb not null default '[]'::jsonb,
  order_time timestamptz not null,
  accepted_at timestamptz,
  preparing_at timestamptz,
  ready_at timestamptz,
  picked_up_at timestamptz,
  updated_at timestamptz not null
);

create index if not exists kitchen_queue_status_idx
  on public.kitchen_order_queue (status, order_time);

create table if not exists public.migration_runs (
  id uuid primary key default extensions.gen_random_uuid(),
  source_name text not null,
  source_fingerprint text not null,
  status text not null check (status in ('running', 'completed', 'completed_with_errors', 'failed')),
  summary jsonb not null default '{}'::jsonb,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  unique (source_name, source_fingerprint)
);

create table if not exists public.migration_failures (
  id bigint generated by default as identity primary key,
  migration_run_id uuid not null references public.migration_runs(id) on delete cascade,
  source_table text not null,
  source_row_number integer,
  legacy_id text,
  error_code text not null,
  error_message text not null,
  source_data jsonb,
  created_at timestamptz not null default now()
);

create index if not exists migration_failures_run_idx
  on public.migration_failures (migration_run_id, source_table);
